### ISSUE TITLE
CVE-2021-37714

### ISSUE THREAD

**Issue by RickMoynihan** [kiranshila/cybermonday#31]
This comes from the hickory dependency, which seems abandoned.

There is an unmerged PR which appears to fix it here: https://github.com/davidsantiago/hickory/pull/62

However it seems it's unlikely to get merged.  In the short term I'd suggest adding a dep on jsoup to cybermonday that bumps to the version in that PR; and we can over the medium/longer term look at forking hickory and ensuring it is adequately maintained (I've skimmed some of the forks and non look like good long term bets).

Is hickory just used for cybermonday on the JVM side of things, or clojurescript too?

**Comment by RickMoynihan** [comment]
FYI have opened an issue on clj-commons to see if we can find a home for it there:

https://github.com/clj-commons/meta/issues/63

**Comment by kiranshila** [comment]
> Is hickory just used for cybermonday on the JVM side of things, or clojurescript too?

It's only used on the JVM side, and I *think* it's only every called when there is a complete HMTL string to parse such that Flexmark recognizes it (including fragments). It's tricky because you can have markdown inside HTML according to the spec, so I parse little chunks of HTML alongside the markdown and try to reassemble them using this code here
https://github.com/kiranshila/cybermonday/blob/673a2e699cc70ddd74e350a7d37274c72dab8ec7/src/cybermonday/ir.cljc#L38-L59
which in my opinion is the jankiest bit on this library.
